<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert([
            // Andhra Pradesh (state_id = 1)
            ['state_id' => 1, 'name' => 'Anantapur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Chittoor', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'East Godavari', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Guntur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Krishna', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Kurnool', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Prakasam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Srikakulam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Visakhapatnam', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'Vizianagaram', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'West Godavari', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 1, 'name' => 'YSR Kadapa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // Arunachal Pradesh (state_id = 2)
            ['state_id' => 2, 'name' => 'Tawang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'West Kameng', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'East Kameng', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Papum Pare', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Kurung Kumey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Kra Daadi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Lower Subansiri', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Upper Subansiri', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'West Siang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'East Siang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Siang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Lower Dibang Valley', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Upper Dibang Valley', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Lower Siang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Upper Siang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'West Kameng', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Anjaw', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Longding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Namsai', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Lepa Rada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Shi Yomi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 2, 'name' => 'Kamle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // Assam (state_id = 3)
            ['state_id' => 3, 'name' => 'Baksa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Barpeta', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Bongaigaon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Cachar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Charaideo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Chirang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Darrang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Dhemaji', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Dhubri', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Dibrugarh', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Goalpara', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Golaghat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Hailakandi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Jorhat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Kamrup', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Kamrup Metropolitan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Karbi Anglong', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Karimganj', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Kokrajhar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Lakhimpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Majuli', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Morigaon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Nagaon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Nalbari', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Sivasagar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Sonitpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Tinsukia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'Udalguri', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 3, 'name' => 'West Karbi Anglong', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // Bihar (state_id = 4)
            ['state_id' => 4, 'name' => 'Araria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Arwal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Aurangabad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Banka', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Begusarai', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Bhagalpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Bhojpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Buxar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Darbhanga', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Gaya', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Gopalganj', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Jamui', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Jehanabad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Kaimur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Katihar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Khagaria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Kishanganj', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Lakhisarai', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Madhepura', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Madhubani', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Munger', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Muzaffarpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Nalanda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Nawada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Patna', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Purnia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Rohtas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Saharsa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Samastipur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Saran', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Sheikhpura', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Sheohar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Sitamarhi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Siwan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Supaul', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'Vaishali', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 4, 'name' => 'West Champaran', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // Chhattisgarh (state_id = 5)
            ['state_id' => 5, 'name' => 'Balod', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Baloda Bazar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Balrampur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Bastar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Bemetara', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Bijapur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Bilaspur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Dantewada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Dhamtari', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Durg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Gariaband', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Janjgir-Champa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Jashpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Kabirdham', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Kanker', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Kondagaon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Korba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Korea', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Mahasamund', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Mungeli', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Narayanpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Raigarh', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Raipur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Rajnandgaon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Sukma', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Surajpur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 5, 'name' => 'Surguja', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // Goa (state_id = 6)
            ['state_id' => 6, 'name' => 'North Goa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 6, 'name' => 'South Goa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // Gujarat (state_id = 7)
            ['state_id' => 7, 'name' => 'Ahmedabad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Amreli', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Anand', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Aravalli', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Banaskantha', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Bharuch', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Bhavnagar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Botad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Chhota Udaipur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Dahod', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Dang', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Gandhinagar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Gir Somnath', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Jamnagar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Junagadh', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Kheda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Kutch', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Mahisagar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Mehsana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Morbi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Narmada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Navsari', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Panchmahal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Patan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Porbandar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Rajkot', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Sabarkantha', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Surat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Surendranagar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Tapi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Vadodara', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 7, 'name' => 'Valsad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['state_id' => 8, 'name' => 'Ambala',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Bhiwani',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Charkhi Dadri', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Faridabad',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Fatehabad',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Gurugram',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Hisar',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Jhajjar',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Jind',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Kaithal',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Karnal',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Kurukshetra',   'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Mahendragarh',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Nuh',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Palwal',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Panchkula',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Panipat',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Rewari',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Rohtak',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Sirsa',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Sonipat',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 8, 'name' => 'Yamunanagar',   'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['state_id' => 9, 'name' => 'Bilaspur',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Chamba',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Hamirpur',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Kangra',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Kinnaur',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Kullu',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Lahaul and Spiti', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Mandi',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Shimla',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Sirmaur',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Solan',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 9, 'name' => 'Una',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],


            ['state_id' => 10, 'name' => 'Bokaro',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Chatra',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Deoghar',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Dhanbad',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Dumka',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'East Singhbhum',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Garhwa',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Giridih',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Godda',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Gumla',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Hazaribagh',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Jamtara',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Khunti',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Koderma',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Latehar',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Lohardaga',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Pakur',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Palamu',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Ramgarh',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Ranchi',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Sahebganj',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Seraikela Kharsawan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'Simdega',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 10, 'name' => 'West Singhbhum',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['state_id' => 11, 'name' => 'Bagalkot',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Ballari',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Belagavi',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Bengaluru Rural', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Bengaluru Urban', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Bidar',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Chamarajanagar',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Chikkaballapur',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Chikkamagaluru',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Chitradurga',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Dakshina Kannada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Davanagere',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Dharwad',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Gadag',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Hassan',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Haveri',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Kalaburagi',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Kodagu',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Kolar',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Koppal',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Mandya',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Mysuru',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Raichur',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Ramanagara',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Shivamogga',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Tumakuru',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Udupi',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Uttara Kannada',  'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Vijayanagara',    'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Vijayapura',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 11, 'name' => 'Yadgir',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            ['state_id' => 12, 'name' => 'Alappuzha',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Ernakulam',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Idukki',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Kannur',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Kasaragod',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Kollam',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Kottayam',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Kozhikode',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Malappuram',    'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Palakkad',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Pathanamthitta', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Thiruvananthapuram', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Thrissur',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 12, 'name' => 'Wayanad',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],


            ['state_id' => 13, 'name' => 'Agar Malwa',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Alirajpur',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Anuppur',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Ashoknagar',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Balaghat',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Barwani',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Betul',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Bhind',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Bhopal',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Burhanpur',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Chhatarpur',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Chhindwara',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Damoh',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Datia',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Dewas',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Dhar',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Dindori',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Guna',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Gwalior',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Harda',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Hoshangabad (Narmadapuram)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Indore',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Jabalpur',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Jhabua',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Katni',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Khandwa',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Khargone',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Mandla',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Mandsaur',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Morena',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Narsinghpur',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Neemuch',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Niwari',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Panna',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Raisen',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Rajgarh',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Ratlam',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Rewa',               'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Sagar',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Satna',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Sehore',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Seoni',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Shahdol',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Shajapur',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Sheopur',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Shivpuri',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Sidhi',              'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Singrauli',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Tikamgarh',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Ujjain',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Umaria',             'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 13, 'name' => 'Vidisha',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],


            ['state_id' => 14, 'name' => 'Ahmednagar',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Akola',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Amravati',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Aurangabad',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Beed',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Bhandara',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Buldhana',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Chandrapur',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Dhule',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Gadchiroli',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Gondia',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Hingoli',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Jalgaon',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Jalna',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Kolhapur',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Latur',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Mumbai City',     'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Mumbai Suburban', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Nagpur',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Nanded',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Nandurbar',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Nashik',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Osmanabad',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Palghar',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Parbhani',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Pune',            'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Raigad',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Ratnagiri',       'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Sangli',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Satara',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Sindhudurg',      'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Solapur',         'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Thane',           'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Wardha',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Washim',          'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['state_id' => 14, 'name' => 'Yavatmal',        'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
