<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('states')->insert([
            ['country_id' => 1, 'name' => 'Andhra Pradesh'],
            ['country_id' => 1, 'name' => 'Arunachal Pradesh'],
            ['country_id' => 1, 'name' => 'Assam'],
            ['country_id' => 1, 'name' => 'Bihar'],
            ['country_id' => 1, 'name' => 'Chhattisgarh'],
            ['country_id' => 1, 'name' => 'Goa'],
            ['country_id' => 1, 'name' => 'Gujarat'],
            ['country_id' => 1, 'name' => 'Haryana'],
            ['country_id' => 1, 'name' => 'Himachal Pradesh'],
            ['country_id' => 1, 'name' => 'Jharkhand'],
            ['country_id' => 1, 'name' => 'Karnataka'],
            ['country_id' => 1, 'name' => 'Kerala'],
            ['country_id' => 1, 'name' => 'Madhya Pradesh'],
            ['country_id' => 1, 'name' => 'Maharashtra'],
            ['country_id' => 1, 'name' => 'Manipur'],
            ['country_id' => 1, 'name' => 'Meghalaya'],
            ['country_id' => 1, 'name' => 'Mizoram'],
            ['country_id' => 1, 'name' => 'Nagaland'],
            ['country_id' => 1, 'name' => 'Odisha'],
            ['country_id' => 1, 'name' => 'Punjab'],
            ['country_id' => 1, 'name' => 'Rajasthan'],
            ['country_id' => 1, 'name' => 'Sikkim'],
            ['country_id' => 1, 'name' => 'Tamil Nadu'],
            ['country_id' => 1, 'name' => 'Telangana'],
            ['country_id' => 1, 'name' => 'Tripura'],
            ['country_id' => 1, 'name' => 'Uttar Pradesh'],
            ['country_id' => 1, 'name' => 'Uttarakhand'],
            ['country_id' => 1, 'name' => 'West Bengal'],

            ['country_id' => 2, 'name' => 'Alabama'],
            ['country_id' => 2, 'name' => 'Alaska'],
            ['country_id' => 2, 'name' => 'Arizona'],
            ['country_id' => 2, 'name' => 'Arkansas'],
            ['country_id' => 2, 'name' => 'California'],
            ['country_id' => 2, 'name' => 'Colorado'],
            ['country_id' => 2, 'name' => 'Connecticut'],
            ['country_id' => 2, 'name' => 'Delaware'],
            ['country_id' => 2, 'name' => 'Florida'],
            ['country_id' => 2, 'name' => 'Georgia'],
            ['country_id' => 2, 'name' => 'Hawaii'],
            ['country_id' => 2, 'name' => 'Idaho'],
            ['country_id' => 2, 'name' => 'Illinois'],
            ['country_id' => 2, 'name' => 'Indiana'],
            ['country_id' => 2, 'name' => 'Iowa'],
            ['country_id' => 2, 'name' => 'Kansas'],
            ['country_id' => 2, 'name' => 'Kentucky'],
            ['country_id' => 2, 'name' => 'Louisiana'],
            ['country_id' => 2, 'name' => 'Maine'],
            ['country_id' => 2, 'name' => 'Maryland'],
            ['country_id' => 2, 'name' => 'Massachusetts'],
            ['country_id' => 2, 'name' => 'Michigan'],
            ['country_id' => 2, 'name' => 'Minnesota'],
            ['country_id' => 2, 'name' => 'Mississippi'],
            ['country_id' => 2, 'name' => 'Missouri'],
            ['country_id' => 2, 'name' => 'Montana'],
            ['country_id' => 2, 'name' => 'Nebraska'],
            ['country_id' => 2, 'name' => 'Nevada'],
            ['country_id' => 2, 'name' => 'New Hampshire'],
            ['country_id' => 2, 'name' => 'New Jersey'],
            ['country_id' => 2, 'name' => 'New Mexico'],
            ['country_id' => 2, 'name' => 'New York'],
            ['country_id' => 2, 'name' => 'North Carolina'],
            ['country_id' => 2, 'name' => 'North Dakota'],
            ['country_id' => 2, 'name' => 'Ohio'],
            ['country_id' => 2, 'name' => 'Oklahoma'],
            ['country_id' => 2, 'name' => 'Oregon'],
            ['country_id' => 2, 'name' => 'Pennsylvania'],
            ['country_id' => 2, 'name' => 'Rhode Island'],
            ['country_id' => 2, 'name' => 'South Carolina'],
            ['country_id' => 2, 'name' => 'South Dakota'],
            ['country_id' => 2, 'name' => 'Tennessee'],
            ['country_id' => 2, 'name' => 'Texas'],
            ['country_id' => 2, 'name' => 'Utah'],
            ['country_id' => 2, 'name' => 'Vermont'],
            ['country_id' => 2, 'name' => 'Virginia'],
            ['country_id' => 2, 'name' => 'Washington'],
            ['country_id' => 2, 'name' => 'West Virginia'],
            ['country_id' => 2, 'name' => 'Wisconsin'],
            ['country_id' => 2, 'name' => 'Wyoming'],

            ['country_id' => 3, 'name' => 'England'],
            ['country_id' => 3, 'name' => 'Scotland'],
            ['country_id' => 3, 'name' => 'Wales'],
            ['country_id' => 3, 'name' => 'Northern Ireland'],

            ['country_id' => 4, 'name' => 'Alberta'],
            ['country_id' => 4, 'name' => 'British Columbia'],
            ['country_id' => 4, 'name' => 'Manitoba'],
            ['country_id' => 4, 'name' => 'New Brunswick'],
            ['country_id' => 4, 'name' => 'Newfoundland and Labrador'],
            ['country_id' => 4, 'name' => 'Nova Scotia'],
            ['country_id' => 4, 'name' => 'Ontario'],
            ['country_id' => 4, 'name' => 'Prince Edward Island'],
            ['country_id' => 4, 'name' => 'Quebec'],
            ['country_id' => 4, 'name' => 'Saskatchewan'],
            ['country_id' => 4, 'name' => 'Northwest Territories'],
            ['country_id' => 4, 'name' => 'Nunavut'],
            ['country_id' => 4, 'name' => 'Yukon'],


            ['country_id' => 5, 'name' => 'New South Wales'],
            ['country_id' => 5, 'name' => 'Victoria'],
            ['country_id' => 5, 'name' => 'Queensland'],
            ['country_id' => 5, 'name' => 'Western Australia'],
            ['country_id' => 5, 'name' => 'South Australia'],
            ['country_id' => 5, 'name' => 'Tasmania'],
            ['country_id' => 5, 'name' => 'Australian Capital Territory'],
            ['country_id' => 5, 'name' => 'Northern Territory'],


            ['country_id' => 6, 'name' => 'Northland'],
            ['country_id' => 6, 'name' => 'Auckland'],
            ['country_id' => 6, 'name' => 'Waikato'],
            ['country_id' => 6, 'name' => 'Bay of Plenty'],
            ['country_id' => 6, 'name' => 'Gisborne'],
            ['country_id' => 6, 'name' => 'Hawke\'s Bay'],
            ['country_id' => 6, 'name' => 'Taranaki'],
            ['country_id' => 6, 'name' => 'Manawatu-Wanganui'],
            ['country_id' => 6, 'name' => 'Wellington'],
            ['country_id' => 6, 'name' => 'Tasman'],
            ['country_id' => 6, 'name' => 'Nelson'],
            ['country_id' => 6, 'name' => 'Marlborough'],
            ['country_id' => 6, 'name' => 'West Coast'],
            ['country_id' => 6, 'name' => 'Canterbury'],
            ['country_id' => 6, 'name' => 'Otago'],
            ['country_id' => 6, 'name' => 'Southland'],

            ['country_id' => 7, 'name' => 'Anhui'],
            ['country_id' => 7, 'name' => 'Beijing'],
            ['country_id' => 7, 'name' => 'Chongqing'],
            ['country_id' => 7, 'name' => 'Fujian'],
            ['country_id' => 7, 'name' => 'Gansu'],
            ['country_id' => 7, 'name' => 'Guangdong'],
            ['country_id' => 7, 'name' => 'Guangxi'],
            ['country_id' => 7, 'name' => 'Guizhou'],
            ['country_id' => 7, 'name' => 'Hainan'],
            ['country_id' => 7, 'name' => 'Hebei'],
            ['country_id' => 7, 'name' => 'Heilongjiang'],
            ['country_id' => 7, 'name' => 'Henan'],
            ['country_id' => 7, 'name' => 'Hubei'],
            ['country_id' => 7, 'name' => 'Hunan'],
            ['country_id' => 7, 'name' => 'Inner Mongolia'],
            ['country_id' => 7, 'name' => 'Jiangsu'],
            ['country_id' => 7, 'name' => 'Jiangxi'],
            ['country_id' => 7, 'name' => 'Jilin'],
            ['country_id' => 7, 'name' => 'Liaoning'],
            ['country_id' => 7, 'name' => 'Ningxia'],
            ['country_id' => 7, 'name' => 'Qinghai'],
            ['country_id' => 7, 'name' => 'Shaanxi'],
            ['country_id' => 7, 'name' => 'Shandong'],
            ['country_id' => 7, 'name' => 'Shanghai'],
            ['country_id' => 7, 'name' => 'Shanxi'],
            ['country_id' => 7, 'name' => 'Sichuan'],
            ['country_id' => 7, 'name' => 'Tianjin'],
            ['country_id' => 7, 'name' => 'Tibet'],
            ['country_id' => 7, 'name' => 'Xinjiang'],
            ['country_id' => 7, 'name' => 'Yunnan'],
            ['country_id' => 7, 'name' => 'Zhejiang'],
            ['country_id' => 7, 'name' => 'Hong Kong'],
            ['country_id' => 7, 'name' => 'Macau'],

        ]);
    }
}
