<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Transfer Challan - {{ $challan->challan_no }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            margin: 20px;
        }

        .header,
        .footer {
            text-align: center;
        }

        .header img {
            max-height: 60px;
            margin-bottom: 10px;
        }

        .header h2 {
            margin: 5px 0;
            font-size: 22px;
            letter-spacing: 1px;
        }

        .info-table,
        .items-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .info-table td {
            padding: 5px;
            vertical-align: top;
        }

        .items-table th,
        .items-table td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }

        .items-table th {
            background-color: #f2f2f2;
        }

        .text-right {
            text-align: right;
        }

        .totals {
            margin-top: 10px;
            width: 100%;
        }

        .totals td {
            padding: 5px;
        }

        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #555;
        }

        @media print {
            body {
                margin: 0;
            }

            .no-print {
                display: none;
            }
        }
    </style>
    <style>
        @media print {
            body {
                font-size: 12px;
            }

            .no-print {
                display: none;
            }
        }
    </style>

</head>

<body>

    <div class="header">
        <!-- Replace with your logo -->
        <img src="{{ asset('admin/assets/img/logo/samrudhi-kirana-logo1.png') }}" alt="Samruddhi Kirana">
        <h2>Transfer Challan</h2>
        <p><strong>Challan No:</strong> {{ $challan->challan_no }}</p>
        <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($challan->transfer_date)->format('d-m-Y') }}</p>
    </div>

    <table class="info-table">
        <tr>
            <td><strong>From Warehouse:</strong> {{ $challan->fromWarehouse->name ?? 'N/A' }}</td>
            <td><strong>To Warehouse:</strong> {{ $challan->toWarehouse->name ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td><strong>Created By:</strong> {{ $challan->created_by }}</td>
            <td><strong>Status:</strong> {{ ucfirst($challan->status) }}</td>
        </tr>
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th>Sr No</th>
                <th>Product Name</th>
                {{-- <th>Batch</th> --}}
                <th class="text-right">Quantity</th>
            </tr>
        </thead>
        <tbody>
            @php $totalQty = 0; @endphp
            @foreach ($challan->items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->product->name ?? 'N/A' }}</td>
                {{-- <td>{{ $item->batch_id ?? '-' }}</td> --}}
                <!-- <td class="text-right">{{ $item->quantity }}</td> -->
                <td class="text-right">{{ number_format($item->quantity, 0) }}</td>
            </tr>
            @php $totalQty += $item->quantity; @endphp
            @endforeach
        </tbody>
    </table>

    <table class="totals">
        <tr>
            <td style="text-align: right;"><strong>Total Quantity:</strong></td>
            <td style="text-align: right;"><strong>{{ $totalQty }}</strong></td>
        </tr>
    </table>

    <div class="footer">
        {{-- <p>Generated by Your Company System</p> --}}
        {{-- <p class="no-print">Use your browser's Print → Save as PDF to download this challan.</p> --}}
    </div>

</body>

<script>
    window.onload = function() {
        window.print();
    };
</script>


</html>